### ISSUE TITLE
Internal server error using get_episodes_from_show

### ISSUE THREAD

**Issue by AevumDecessus** [NickMolloy/rt_api#12]
Python version 3.6
rt-api version 1.1.1

```python
#!/usr/bin/env python3
import argparse 
import rt_api.models
from rt_api.api import Api

api = Api()
api.authenticate('MYUSERNAME', 'MYPASSWORD') 

bad_urls = [
  'https://roosterteeth.com/episode/red-vs-blue-season-10-psa-online-survival',
  'https://roosterteeth.com/episode/red-vs-blue-season-1-psa-4',
  ]

def get_episodes_from_show(show_id, verbose):
  _episodes = []
  if verbose:
    print(f"Fetching seasons for show {show_id}")
  seasons = api.show_seasons(show_id)
  for season in seasons:
    if verbose:
      print(f"Fetching episodes in season {season.number}")
    episodes = api.season_episodes(season.id_)
    _episodes.extend(episodes)
  return _episodes

def write_episodes_to_file(filename, show_id, verbose):
  if verbose:
    print(f"Fetching all episodes for show {show_id}")
  eps = get_episodes_from_show(show_id, verbose)
  if verbose:
    print(f"Writing episodes to file {filename}")
  f = open(filename, "w")
  for ep in eps:
    if not ep.canonical_url in bad_urls:
      f.write(str(ep.canonical_url) + "\n")
    else:
      print(f"Skipping {ep.canonical_url} as it's a bad URL")
  f.close()

parser = argparse.ArgumentParser(description="Fetch all episodes of roosterteeth series")
parser.add_argument('--show-id', required=True)
parser.add_argument('--store-file', required=True)
parser.add_argument('--verbose', action='store_true')
args = parser.parse_args()

write_episodes_to_file(args.store_file, args.show_id, args.verbose)

```
Passing "rwby" or "34" as show_id, I get the following stack trace

```
(get_urls) [aevum@files get_urls]$ python get3.py --show-id "rwby" --store-file test.txt --verbose
Fetching all episodes for show rwby
Fetching seasons for show rwby
Traceback (most recent call last):
  File "get3.py", line 52, in <module>
    write_episodes_to_file(args.store_file, args.show_id, args.verbose)
  File "get3.py", line 35, in write_episodes_to_file
    eps = get_episodes_from_show(show_id, verbose)
  File "get3.py", line 24, in get_episodes_from_show
    seasons = api.show_seasons(show_id)
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 331, in show_seasons
    return self.__get_multiple(models.Season, "shows/{0}/seasons/".format(show_id))
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 231, in __get_multiple
    data = self.__get_data(url, kwargs)
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 193, in __get_data
    response.raise_for_status()
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://roosterteeth.com/api/v1/shows/rwby/seasons/
```
```
(get_urls) [aevum@files get_urls]$ python get3.py --show-id 34 --store-file test.txt --verbose
Fetching all episodes for show 34
Fetching seasons for show 34
Traceback (most recent call last):
  File "get3.py", line 52, in <module>
    write_episodes_to_file(args.store_file, args.show_id, args.verbose)
  File "get3.py", line 35, in write_episodes_to_file
    eps = get_episodes_from_show(show_id, verbose)
  File "get3.py", line 24, in get_episodes_from_show
    seasons = api.show_seasons(show_id)
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 331, in show_seasons
    return self.__get_multiple(models.Season, "shows/{0}/seasons/".format(show_id))
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 231, in __get_multiple
    data = self.__get_data(url, kwargs)
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/rt_api/api.py", line 193, in __get_data
    response.raise_for_status()
  File "/home/aevum/.local/share/virtualenvs/get_urls-Ains_FWy/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://roosterteeth.com/api/v1/shows/34/seasons/
```

Same errors using other show_ids such as "1" or "red-vs-blue"

**Comment by JustEnoughDucks** [comment]
What I coincidence, I just started playing around with this api, today.

Using the example code:

```
from rt_api.api import Api

api = Api() # Instantiate api
api.authenticate("myUsername", "PASSWORD")  # Authenticate as myUsername
latest_episodes = api.episodes()  # Get an iterable of the latest episodes
newest_episode = next(latest_episodes)
print(newest_episode.title)  # Print out episode title
show = newest_episode.show  # Get a reference to the show the episode is from
print(show.name)  # Print out name of the show
```

I get the same traceback errors with Python 3.9.1

500 Server Error: Internal Server Error for url: https://roosterteeth.com/api/v1/feed/?page=1&count=20&type=Episode

I checked to make sure authentication is correct and `api.me` works to get my profile information and FIRST status, but fails calling `api.episodes()`

if you go on your browser to [https://roosterteeth.com/api/v1/shows/34](https://roosterteeth.com/api/v1/shows/34), you get a error: `{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}`

They have possibly implemented a new access token associated to accounts that make you able to access the api? I don't think it is actually related to this api.

When did this problem start for you? I think it was a week ago or so that I was checking out the api via web browser and it was working.
